server:
  port: 8080
spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            scope:
              - account_email
              - profile_nickname
              - profile_image
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao" # 추후 수정 필요
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  profiles:
    include: secret
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        default_batch_fetch_size: 1000
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
custom:
  jwt:
    access:
      expiration: 1800000 # 30분
      header: Authorization
    refresh:
      expiration: 604800000 #  일주일
      header: Authorization-refresh
